name: flutter_fb
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.5.0
  intl: ^0.20.1
  provider: ^6.1.2
  flutter_naver_map: ^1.3.0+1
  http: ^1.1.0
  webview_flutter: ^4.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true