// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAytqDDhDuNnT2ID9lPGvFyOwsT4T4uhxw',
    appId: '1:396928344624:web:987bb8f5a4c503c4cf83f5',
    messagingSenderId: '396928344624',
    projectId: 'flutter-group5',
    authDomain: 'flutter-group5.firebaseapp.com',
    storageBucket: 'flutter-group5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbZfwTmM9pGQdcru3i7yD0WobnHbY_jes',
    appId: '1:396928344624:android:fe2f6d3d3d6f603acf83f5',
    messagingSenderId: '396928344624',
    projectId: 'flutter-group5',
    storageBucket: 'flutter-group5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIj5yPh7jXhPRORgtnYYZazuZp1SBb_zk',
    appId: '1:396928344624:ios:13c83b9714663272cf83f5',
    messagingSenderId: '396928344624',
    projectId: 'flutter-group5',
    storageBucket: 'flutter-group5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIj5yPh7jXhPRORgtnYYZazuZp1SBb_zk',
    appId: '1:396928344624:ios:13c83b9714663272cf83f5',
    messagingSenderId: '396928344624',
    projectId: 'flutter-group5',
    storageBucket: 'flutter-group5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAytqDDhDuNnT2ID9lPGvFyOwsT4T4uhxw',
    appId: '1:396928344624:web:916b1341efa739fecf83f5',
    messagingSenderId: '396928344624',
    projectId: 'flutter-group5',
    authDomain: 'flutter-group5.firebaseapp.com',
    storageBucket: 'flutter-group5.firebasestorage.app',
  );

}